### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sdvcrx** [banbanchs/hexo-theme-whitespace#1]
Todo List:
- [ ] Add post link to `<time>`
- [x] Code block style
- [ ] Code highlight
- [x] Pullquote left/right
- [x] Gallery post support
- [ ] Link post support
- [x] Twitter sharing
- [x] `span.caption` style
- [x] `video-container` style
- [x] GFM table style
- [ ] i18n
- [ ] Optimization for chinese
